version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: web-chat-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "web_chat"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.4
    container_name: web-chat-redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "123456"]
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: web-chat-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro

volumes:
  mysql_data:
  redis_data:
